In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('../sample1.csv')

In [3]:
df.head(9)

Sno             Name   Age   Salary        Designation      Mobile
0    1    Shabeeh Abbas  28.0   $82300     senior manager  9080706050
1    2  Kashish Jaiswal  21.0   $70000            manager  8798677809
2    3       Arsh singh   NaN   $64000     senior manager  8490765689
3    4     kriti rajput  25.0   $89000            manager  9987650044
4    5     nisha shukla  26.0   $58000  assistant manager  8976456001
5    6    pashant singh  22.0   $75000            manager  7767890022
6    7       aishwarya    NaN   $65000     senior manager  7645678900
7    8      anjani soni  23.0   $70980            manager  8900012333
8    9     aditya verma  24.0  $456700  assistant manager  9087666340

In [4]:
df.isnull()

Sno   Name    Age  Salary  Designation  Mobile
0  False  False  False   False        False   False
1  False  False  False   False        False   False
2  False  False   True   False        False   False
3  False  False  False   False        False   False
4  False  False  False   False        False   False
5  False  False  False   False        False   False
6  False  False   True   False        False   False
7  False  False  False   False        False   False
8  False  False  False   False        False   False
9  False  False  False   False        False   False

In [5]:
df.isnull().sum()

Sno            0
Name           0
Age            2
Salary         0
Designation    0
Mobile         0
dtype: int64

In [6]:
def salary_clean(salary):
    if isinstance(salary,str):
        salary=salary.strip()
        if '$' in salary:
            salary=salary.replace('$','')
        if ',' in salary:
            salary=salary.replace(',','')
        return int(salary)
    return salary


In [7]:
df['Salary'].apply(salary_clean)

0     82300
1     70000
2     64000
3     89000
4     58000
5     75000
6     65000
7     70980
8    456700
9    560000
Name: Salary, dtype: int64

In [8]:
df['Salary']=df['Salary'].apply(salary_clean)
df

Sno             Name   Age  Salary        Designation      Mobile
0    1    Shabeeh Abbas  28.0   82300     senior manager  9080706050
1    2  Kashish Jaiswal  21.0   70000            manager  8798677809
2    3       Arsh singh   NaN   64000     senior manager  8490765689
3    4     kriti rajput  25.0   89000            manager  9987650044
4    5     nisha shukla  26.0   58000  assistant manager  8976456001
5    6    pashant singh  22.0   75000            manager  7767890022
6    7       aishwarya    NaN   65000     senior manager  7645678900
7    8      anjani soni  23.0   70980            manager  8900012333
8    9     aditya verma  24.0  456700  assistant manager  9087666340
9   10     sneha shukla  21.0  560000            manager  8900044559

In [9]:
df.dropna()

Sno             Name   Age  Salary        Designation      Mobile
0    1    Shabeeh Abbas  28.0   82300     senior manager  9080706050
1    2  Kashish Jaiswal  21.0   70000            manager  8798677809
3    4     kriti rajput  25.0   89000            manager  9987650044
4    5     nisha shukla  26.0   58000  assistant manager  8976456001
5    6    pashant singh  22.0   75000            manager  7767890022
7    8      anjani soni  23.0   70980            manager  8900012333
8    9     aditya verma  24.0  456700  assistant manager  9087666340
9   10     sneha shukla  21.0  560000            manager  8900044559

In [10]:
df.drop(['Mobile','Name','Sno'],axis=1,inplace=True) #this will make changes to original data

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
imputer=SimpleImputer()


In [13]:
#trial run
cols=['Age','Salary']
imputer.fit_transform(df[cols])

array([[2.800e+01, 8.230e+04],
       [2.100e+01, 7.000e+04],
       [2.375e+01, 6.400e+04],
       [2.500e+01, 8.900e+04],
       [2.600e+01, 5.800e+04],
       [2.200e+01, 7.500e+04],
       [2.375e+01, 6.500e+04],
       [2.300e+01, 7.098e+04],
       [2.400e+01, 4.567e+05],
       [2.100e+01, 5.600e+05]])

In [14]:
#actual run
cols=['Age','Salary']
df[cols]=imputer.fit_transform(df[cols])

In [15]:
df

Age    Salary        Designation
0  28.00   82300.0     senior manager
1  21.00   70000.0            manager
2  23.75   64000.0     senior manager
3  25.00   89000.0            manager
4  26.00   58000.0  assistant manager
5  22.00   75000.0            manager
6  23.75   65000.0     senior manager
7  23.00   70980.0            manager
8  24.00  456700.0  assistant manager
9  21.00  560000.0            manager

In [16]:
df['Designation'].value_counts()

manager              5
senior manager       3
assistant manager    2
Name: Designation, dtype: int64

In [17]:
#trial run
imp2=SimpleImputer(strategy='most_frequent')
imp2.fit_transform(df[['Designation']])


array([['senior manager'],
       ['manager'],
       ['senior manager'],
       ['manager'],
       ['assistant manager'],
       ['manager'],
       ['senior manager'],
       ['manager'],
       ['assistant manager'],
       ['manager']], dtype=object)

In [18]:
#actual run

df['Designation']=imp2.fit_transform(df[['Designation']])


In [19]:
gender=['male','female']*5

In [20]:
df['Gender']=gender# adding column

In [21]:
df

Age    Salary        Designation  Gender
0  28.00   82300.0     senior manager    male
1  21.00   70000.0            manager  female
2  23.75   64000.0     senior manager    male
3  25.00   89000.0            manager  female
4  26.00   58000.0  assistant manager    male
5  22.00   75000.0            manager  female
6  23.75   65000.0     senior manager    male
7  23.00   70980.0            manager  female
8  24.00  456700.0  assistant manager    male
9  21.00  560000.0            manager  female

In [22]:
df.rename({'Salary':'Pay'},axis=1,inplace=True)

In [23]:
df

Age       Pay        Designation  Gender
0  28.00   82300.0     senior manager    male
1  21.00   70000.0            manager  female
2  23.75   64000.0     senior manager    male
3  25.00   89000.0            manager  female
4  26.00   58000.0  assistant manager    male
5  22.00   75000.0            manager  female
6  23.75   65000.0     senior manager    male
7  23.00   70980.0            manager  female
8  24.00  456700.0  assistant manager    male
9  21.00  560000.0            manager  female

In [24]:
df.loc[0]

Age                      28.0
Pay                   82300.0
Designation    senior manager
Gender                   male
Name: 0, dtype: object

In [25]:
row=[{'Age':19,'Pay':19000,'Designation':'manager','Gender':'male'}]

In [26]:
df=df.append(row,ignore_index=1)

C:\Users\KASHISH JAISWAL\AppData\Local\Temp\ipykernel_104\4020514037.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(row,ignore_index=1)


In [27]:
df

Age       Pay        Designation  Gender
0   28.00   82300.0     senior manager    male
1   21.00   70000.0            manager  female
2   23.75   64000.0     senior manager    male
3   25.00   89000.0            manager  female
4   26.00   58000.0  assistant manager    male
5   22.00   75000.0            manager  female
6   23.75   65000.0     senior manager    male
7   23.00   70980.0            manager  female
8   24.00  456700.0  assistant manager    male
9   21.00  560000.0            manager  female
10  19.00   19000.0            manager    male

In [28]:
df['Gender'].value_counts()

male      6
female    5
Name: Gender, dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
gender_enc = LabelEncoder()
gender_enc.fit(df['Gender'])

LabelEncoder()

In [31]:
gender_enc.transform(df['Gender'])

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [32]:
df['Gender'] = gender_enc.transform(df['Gender'])
df

Age       Pay        Designation  Gender
0   28.00   82300.0     senior manager       1
1   21.00   70000.0            manager       0
2   23.75   64000.0     senior manager       1
3   25.00   89000.0            manager       0
4   26.00   58000.0  assistant manager       1
5   22.00   75000.0            manager       0
6   23.75   65000.0     senior manager       1
7   23.00   70980.0            manager       0
8   24.00  456700.0  assistant manager       1
9   21.00  560000.0            manager       0
10  19.00   19000.0            manager       1

In [33]:
gender_enc.classes_

array(['female', 'male'], dtype=object)

In [34]:
gender_enc.inverse_transform([0,1,1]) # decode

array(['female', 'male', 'male'], dtype=object)

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
desig_enc=OneHotEncoder()
desig_enc.fit(df[['Designation']])


OneHotEncoder()

In [37]:
designation_dummy=desig_enc.transform(df[['Designation']]).toarray()
designation_dummy

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [38]:
df.drop(columns=['Designation'],axis=1,inplace=True)

In [39]:
import numpy as np

In [40]:
data=np.hstack((designation_dummy,df.values))
data.shape

(11, 6)

In [41]:
##option 2 better way
desig_dummy_df=pd.DataFrame(designation_dummy)
desig_dummy_df.head()

0    1    2
0  0.0  0.0  1.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
3  0.0  1.0  0.0
4  1.0  0.0  0.0

In [42]:
data_df=pd.concat([desig_dummy_df,df],axis=1)

In [43]:
data_df

0    1    2    Age       Pay  Gender
0   0.0  0.0  1.0  28.00   82300.0       1
1   0.0  1.0  0.0  21.00   70000.0       0
2   0.0  0.0  1.0  23.75   64000.0       1
3   0.0  1.0  0.0  25.00   89000.0       0
4   1.0  0.0  0.0  26.00   58000.0       1
5   0.0  1.0  0.0  22.00   75000.0       0
6   0.0  0.0  1.0  23.75   65000.0       1
7   0.0  1.0  0.0  23.00   70980.0       0
8   1.0  0.0  0.0  24.00  456700.0       1
9   0.0  1.0  0.0  21.00  560000.0       0
10  0.0  1.0  0.0  19.00   19000.0       1

In [44]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [45]:
mxScaler=MinMaxScaler()
mxScaler.fit(data_df)
scaled_data=mxScaler.transform(data_df)
print(scaled_data)

[[0.         0.         1.         1.         0.11700555 1.        ]
 [0.         1.         0.         0.22222222 0.09426987 0.        ]
 [0.         0.         1.         0.52777778 0.0831793  1.        ]
 [0.         1.         0.         0.66666667 0.12939002 0.        ]
 [1.         0.         0.         0.77777778 0.07208872 1.        ]
 [0.         1.         0.         0.33333333 0.10351201 0.        ]
 [0.         0.         1.         0.52777778 0.08502773 1.        ]
 [0.         1.         0.         0.44444444 0.09608133 0.        ]
 [1.         0.         0.         0.55555556 0.8090573  1.        ]
 [0.         1.         0.         0.22222222 1.         0.        ]
 [0.         1.         0.         0.         0.         1.        ]]


C:\Users\KASHISH JAISWAL\Miniconda3\envs\digi\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\KASHISH JAISWAL\Miniconda3\envs\digi\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [46]:
# this is used in Coding
stdScaler = StandardScaler()
stdScaler.fit(data_df)
scaled_data = stdScaler.transform(data_df)
print(scaled_data)

[[-0.47140452 -1.09544512  1.63299316  1.94080699 -0.37051357  0.91287093]
 [-0.47140452  0.91287093 -0.61237244 -0.9609821  -0.44165293 -1.09544512]
 [-0.47140452 -1.09544512  1.63299316  0.17900647 -0.47635506  0.91287093]
 [-0.47140452  0.91287093 -0.61237244  0.69718309 -0.33176286 -1.09544512]
 [ 2.12132034 -1.09544512 -0.61237244  1.11172439 -0.51105718  0.91287093]
 [-0.47140452  0.91287093 -0.61237244 -0.5464408  -0.41273449 -1.09544512]
 [-0.47140452 -1.09544512  1.63299316  0.17900647 -0.47057137  0.91287093]
 [-0.47140452  0.91287093 -0.61237244 -0.1318995  -0.43598491 -1.09544512]
 [ 2.12132034 -1.09544512 -0.61237244  0.28264179  1.79489921  0.91287093]
 [-0.47140452  0.91287093 -0.61237244 -0.9609821   2.39235418 -1.09544512]
 [-0.47140452  0.91287093 -0.61237244 -1.7900647  -0.73662102  0.91287093]]


C:\Users\KASHISH JAISWAL\Miniconda3\envs\digi\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\KASHISH JAISWAL\Miniconda3\envs\digi\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
